{% set name = "bert_score" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffc1927dc7ea1ede0db8c767a2351d70172236f3ad50ed90b22ffb946e5a59e2

build:
  number: 0
  entry_points:
    - bert-score=bert_score_cli.score:main
    - bert-score-show=bert_score_cli.visualize:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - pandas >=1.0.1
    - python
    - requests
    - pytorch >=1.0.0
    - tqdm >=4.31.1
    - transformers
    - dataclasses

test:
  imports:
    - bert_score
    - bert_score_cli
  commands:
    - bert-score --help
    - bert-score-show --help
  requires:
    - pytest

about:
  home: https://github.com/Tiiiger/bert_score
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyTorch implementation of BERT score
  doc_url: https://pypi.org/project/bert-score/
  dev_url: https://github.com/Tiiiger/bert_score

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
